---
 lookback_days: 10
 epoch: 50
 input_size: 768
 batch_size: 128
 attn_type: "vanilla"
 learnable_curvature: false
 init_curvature_value: 1.0
 patience: 7
 hidden_dim: 128
 lr: 0.0005
 unit: 30
 hyp_lstm: true
 time_param: false
 model_dir: /root/sanchit/research-group/saved_models/vanilla_10_0.3248942213793019_hyp_lstm-True_learnable_curvature-False_init_curvature_value-1.0_unit-30.pt
 results_dir: /root/sanchit/research-group/results_suicide_test/
